#!/bin/bash

set -u
set -e

RTL=$TOP/rtl
BENCH=$TOP/bench

verif() {
	echo "VRFY $BENCH/verilog/$1.v"
	cd $BENCH/verilog
	iverilog -y $RTL/verilog $1.v
	./a.out | grep PASS > /dev/null
}

cleanup() {
	rm a.out *.vcd
}

for x in GPIA_BIT GPIA_BYTE; do
	if ! (verif $x); then
		echo "FAIL"
		exit 1
	fi
done

(cd $BENCH/verilog && cleanup)
