#!/bin/bash

set -u
set -e

RTL=$TOP/rtl
BENCH=$TOP/bench

verif() {
	echo "VRFY $BENCH/verilog/$1.v"
	cd $BENCH/verilog
	iverilog -y $RTL/verilog $1.v
	./a.out | grep PASS > /dev/null
}

cleanup() {
	rm a.out *.vcd
}

if ! (verif GPIA_BIT); then
	echo "FAIL"
	exit 1
fi

(cd $BENCH/verilog && cleanup)

